# Generated by Django 3.2.11 on 2024-01-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('Proposal_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Category', models.CharField(max_length=255)),
                ('Title', models.CharField(max_length=255)),
                ('Budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Status', models.BooleanField(default=False)),
            ],
        ),
    ]
