# Generated by Django 3.2.11 on 2024-01-04 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalField',
            fields=[
                ('Proposal_Field_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Topic', models.CharField(max_length=255)),
                ('Member1', models.CharField(max_length=255)),
                ('Member2', models.CharField(max_length=255)),
                ('Member3', models.CharField(max_length=255)),
                ('Proposal_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.proposal')),
            ],
        ),
    ]
